[package]
name = "mac-rf"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }

crc = "3.2"
cobs = "0.3"
embedded-io-async = "0.6"

bitfield-struct = "0.10"
endian-num = { version = "0.2", features = ["linux-types"] }

[dev-dependencies]
embassy-sync = "0.6.2"
embassy-futures = "0.1.1"

async-std = { version = "1.13", features = ["attributes"] }

pretty_env_logger = "0.5.0"

[features]
defmt = ["dep:defmt"]
log = ["dep:log"]